#! /bin/sh
#
# kill for restarting bspwm
killall -q picom
killall -q fehbg
killall -q polybar

pgrep -x sxhkd > /dev/null || sxhkd &

# depending on the laptop, it will be either eDP1 or eDP-1
# run xrandr --current to check
if [[ $(xrandr -q | grep -w connected | grep "DisplayPort-2") ]]
then
  bspc monitor DisplayPort-2 -d 1 2 3 4 5
  bspc monitor eDP -d 6 7 8 9
else
  bspc monitor eDP -d 1 2 3 4 5 6 7 8 9
fi

# borders
bspc config border_width         2
bspc config focused_border_color "#E5C38F"
bspc config normal_border_color "#423B31"

bspc config top_padding	0
bspc config window_gap          14
bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config focus_follows_pointer true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# startup stuff
## compositor
picom -b
## background
~/.fehbg &
## polybar
polybar leftbar &
polybar rightbar &
udiskie &

if [[ $(xrandr -q | grep -w connected | grep "DisplayPort-2") ]]
then
    polybar midbar &
fi
