#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
PS1='[\u@\h \W]\$ '
alias ll="ls -l"
alias v="nvim"
alias ..="cd .."
alias ux='chmod u+x'
alias mkdir='mkdir -p'

alias ziptar="tar -zcvf"
alias unziptar="tar -xvzf"

alias gadd='git add'
alias gdiff='git diff'
alias mpush='git push origin master'
alias gstat='git status'
function gcom() {
    GITMESSAGE="$*"
    git commit -m "$GITMESSAGE"
}

alias ll='exa -lg --icons'
alias lll='exa -lga'
alias cat='bat --style=header,grid'

export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$HOME/go/bin"

eval "$(fnm env --use-on-cd)"

eval "$(starship init bash)"
pass() {
    (cd /home/kokopi/kp/syncpass && bash /home/kokopi/kp/syncpass/syncpass "$@")
}
export PASSWORD_STORE_EXTENSION_COMMANDS=("c")
__password_store_extension_complete_c() {
    COMPREPLY+=($(compgen -W "-o --option" -- ${cur}))
    _pass_complete_entries 1
}

export GTK_THEME=tokyonight-dark

bind 'TAB:menu-complete'
bind 'set show-all-if-ambiguous on'

eval "$(fzf --bash)"
export FZF_CTRL_T_COMMAND="fd --type f --type d --hidden --follow --exclude .git --exclude venv --exclude node_modules --exclude .cache --exclude cache --exclude __pycache__ --exclude pkg --exclude .vim --exclude .themes --exclude .cargo --exclude .config/discord --exclude .npm --exclude .mozilla --exclude .rustup --search-path ."

