# BACKGROUND
background {
    monitor =
    path = ~/pictures/bgs/neco1.png
    blur_passes = 2
    blur_size = 1
    contrast = 1.0
    brightness = 0.45
    vibrancy = 0.1
    vibrancy_darkness = 0.0
}

# GENERAL
general {
    hide_cursor = true
}

# small box background
shape {
    monitor = 
    size = 350, 320
    color = rgba(24, 12, 31, 0.45)
    rounding = 8
    border_size = 3
    border_color = rgba(255, 255, 255, 0.2)
    rotate = 0
    xray = false

    position = 0, -45
    halign = center
    valign = center
}
shape {
    monitor = 
    size = 350, 3
    color = rgba(230, 212, 230, 0.5)
    position = 0, 35
}

# date
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%m/%d - %H:%M:%S")"
    color = rgb(230, 212, 230)
    font_size = 18
    font_family = Geist Light
    position = 0, 75
    halign = center
    valign = center
    shadow_passes = 1
    shadow_size = 5
    shadow_boost = 0.5
}

# PICTURE
image {
    path = ~/pictures/profile_pics/biyo.png
    size = 100
    position = 0, -30
    halign = center
    valign = center
    border_size = 0
    # border_color = rgb(230, 212, 230)
    shadow_passes = 1
    shadow_size = 5
    shadow_boost = 0.5
}

# USER
label {
    monitor =
    text = cmd[update:1000] echo "$USER@$HOSTNAME"
    color = rgb(230, 212, 230)
    font_size = 14
    font_family = Geist Semibold
    position = 0, -110
    halign = center
    valign = center
    shadow_passes = 1
    shadow_size = 5
    shadow_boost = 0.5
}

input-field {
    monitor =
    size = 256, 48
    outline_thickness = 0
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.5 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = rgba(00000000)
    inner_color = rgba(0, 0, 0, 1)
    font_color = rgb(230, 212, 230)
    fail_color = rgb(192, 149, 149)
    check_color = rgb(149, 203, 173)
    capslock_color = rgb(149, 182, 203)
    fade_on_empty = false
    font_family = Noto Sans
    placeholder_text = ... #text for input password
    hide_input = false
    position = 0, -155
    halign = center
    valign = center
    shadow_passes = 1
    shadow_size = 5
    shadow_boost = 0.5
}
